main/urls.py
from django.contrib import admin
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('home/<int:data_code>/', views.product_detail, name='product_detail'),

    path('home/upload_img/', views.upload_image, name='upload_image'),
    path('home/upload_code/', views.upload_code, name='upload_code'),


    path('home/data_list/', views.data_list, name='data_list'),
    path('home/data_add/', views.data_add, name='data_add'),
    path('home/data/<int:data_code>/', views.data_detail, name='data_detail'),
    path('home/<int:data_code>/update/', views.data_update, name='data_update'), 
    path('home/<int:data_code>/delete/', views.data_delete, name='data_delete'),
    path('home/result', views.result, name='result'),

    path('home/<int:post_id>/comments/create/', views.comments_create, name='comments_create'),
    path('home/<int:post_id>/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:data_code>/like/', views.like, name='like'),
    path('<int:data_code>/vote/', views.vote, name='vote'),

    path('home/introduce/', views.introduce, name='introduce'),

    path('home/cal_result', views.cal_result, name='cal_result'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from user import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('user.urls', namespace='user')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Bar_code(models.Model):
    code = models.CharField(max_length=20, primary_key=True, null=False)
    charge = models.IntegerField(null=False)
    name = models.CharField(max_length=30, null=False)
    image = models.ImageField(blank=True, null=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    id = models.IntegerField(blank=True, null=True)
    # author = models.ForeignKey(related_name='bar_code_set', on_delete=models.CASCADE)

    total = models.IntegerField(blank=True, null=True)
    provision = models.FloatField(blank=True, null=True)
    kcal = models.FloatField(blank=True, null=True)
    carbo = models.FloatField(blank=True, null=True)
    sugar = models.FloatField(blank=True, null=True)
    protein = models.FloatField(blank=True, null=True)
    fat = models.FloatField(blank=True, null=True)
    sat_fat = models.FloatField(blank=True, null=True)
    tra_fat = models.FloatField(blank=True, null=True)
    colestrol = models.FloatField(blank=True, null=True)
    natrium = models.FloatField(blank=True, null=True)


    def __str__(self):
        return self.name

class Upload_Img(models.Model):
    image = models.ImageField()
    pub_date = models.DateTimeField('date published', default=timezone.now)

class Upload_Code(models.Model):
    title = models.CharField(max_length=20)
    pub_date = models.DateTimeField('date published', default=timezone.now)

class Review(models.Model):
    code_name = models.ForeignKey(Bar_code, on_delete=models.CASCADE) # 외래키이므로 위에 question을 참조하고 삭제되면 같이 삭제
    review_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.review_text

class Choice(models.Model):
    code_name = models.ForeignKey(Bar_code, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Upload(models.Model):
    image = models.FileField()

main/forms.py
from django import forms

from .models import Bar_code, Upload_Img, Upload_Code, Upload, Review
from django.forms import ClearableFileInput

class PostForm(forms.ModelForm):

    class Meta:
        model = Bar_code
        fields = ('code', 'name', 'charge', 'image',)

class UploadForm_Img(forms.ModelForm):
    
    class Meta:
        model = Upload_Img
        fields = ( 'image', )

class UploadForm_Code(forms.ModelForm):
    
    class Meta:
        model = Upload_Code
        fields = ( 'title', )


class Multi_Upload(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['image']
        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True}),
        }

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['review_text']

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import PostForm, UploadForm_Img, UploadForm_Code, Multi_Upload, ReviewForm
from django.utils import timezone

from main.models import Bar_code, Upload_Img, Upload_Code, Upload, Review, Choice
from .bar_read import bar_read
from django.conf import settings


# Create your views here.

def index(request):
    return render(request, 'index.html')

def home(request):
    code_list = Bar_code.objects.order_by('-pub_date')[:]
    return render(request, 'home.html', {'code_list':code_list})

def product_detail(request, data_code):
    post = get_object_or_404(Bar_code, pk=data_code)
    return render(request, 'product_detail.html', {'post': post})



def upload_image(request):
    if request.method == 'POST':
        form = UploadForm_Img(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            imageURL = settings.MEDIA_URL + form.instance.image.name
            tmp = settings.MEDIA_ROOT_URL + imageURL
            post.save()
            if tmp:
                result = bar_read(tmp)
                if result == Bar_code.objects.get(pk=result).pk:
                    return HttpResponseRedirect(reverse('main:product_detail',  args=(result,)))
    else:
        form = UploadForm_Img()
    return render(request, 'upload_img.html', {'form':form})

def upload_code(request):
    if request.method == 'POST':
        form = UploadForm_Code(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            # post.pub_date = timezone.now()
            # post.save()
            result = post.title
            # try:
            if result == Bar_code.objects.get(pk=result).pk:
                return HttpResponseRedirect(reverse('main:product_detail',  args=(result,)))
            # except (KeyError, Choice.DoesNotExist):
            #     return render(request, 'upload_text.html', {'error_message': "Nothing DB",})
    else:
        form = UploadForm_Code()
    return render(request, 'upload_text.html', {'form':form})





def data_list(request):
    code_list = Bar_code.objects.order_by('-pub_date')[:]
    return render(request, 'data_list.html', {'code_list':code_list})

def data_add(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            # post.author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('/home/data_list')
    else:
        form = PostForm()
    return render(request, 'data_add.html', {'form': form})

def data_detail(request, data_code): 
    post = get_object_or_404(Bar_code, pk=data_code)
    return render(request, 'data_detail.html', {'post': post})

def data_update(request, data_code):
    post = get_object_or_404(Bar_code, pk=data_code)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            # post.author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('/home/data_list')
    else:
        form = PostForm(instance=post)
    return render(request, 'data_add.html', {'form': form})

def data_delete(request, data_code):
    post = Bar_code.objects.get(pk=data_code)
    post.delete()
    return redirect('/home/data_list')





def result(request):
    if request.method == "POST":
        form = Multi_Upload(request.POST, request.FILES)
        files = request.FILES.getlist('image')
        result = 0
        bar_list = []
        if form.is_valid():
            for f in files:
                file_instance = Upload(image=f)
                file_instance.save()   
                imageURL = settings.MEDIA_URL + str(f)
                tmp = settings.MEDIA_ROOT_URL + imageURL
                form.save()
                if tmp:
                    res = bar_read(tmp)
                    if res == Bar_code.objects.get(pk=res).pk:
                        result += Bar_code.objects.get(pk=res).charge
                        bar_list.append("코드: " + str(Bar_code.objects.get(pk=res).code) +" \t상품명: "+ Bar_code.objects.get(pk=res).name +" \t가격: "+ str(Bar_code.objects.get(pk=res).charge))
            return render(request, 'result.html', {'result': result, 'bar_list':bar_list})
    else:
        form = Multi_Upload()
    return render(request, 'upload_img_total.html', {'form': form})





def comments_create(request, post_id):
    post = Bar_code.objects.get(pk=post_id).pk
    content = request.POST.get('content')
    comment = Review(code_name_id=int(post), review_text=content)
    comment.save()

    return HttpResponseRedirect(reverse('main:product_detail', args=(post_id,)))

def comments_delete(request, post_id, comment_id):
    comment = Review.objects.get(pk=comment_id)
    comment.delete()
    
    return HttpResponseRedirect(reverse('main:product_detail', args=(post_id,)))



 


def like(request, data_code):
    post = get_object_or_404(Bar_code, pk=data_code)
    return render(request, 'like.html', {'post': post})

def vote(request, data_code):
    post = get_object_or_404(Bar_code, pk=data_code)
    try:
        selected_choice = post.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'product_detail.html', {
            'post': post,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('main:product_detail', args=(data_code,)))

def introduce(request):
    return render(request,'introduce.html')

def cal_result(request):
    if request.method == "POST":
        form = Multi_Upload(request.POST, request.FILES)
        files = request.FILES.getlist('image')
        result1 = 0
        result2 = 0
        result3 = 0
        result4 = 0
        result5 = 0
        bar_list = []
        if form.is_valid():
            for f in files:
                file_instance = Upload(image=f)
                file_instance.save()   
                imageURL = settings.MEDIA_URL + str(f)
                tmp = settings.MEDIA_ROOT_URL + imageURL
                form.save()
                if tmp:
                    res = bar_read(tmp)
                    if res == Bar_code.objects.get(pk=res).pk:
                        result1 += Bar_code.objects.get(pk=res).total
                        result2 += Bar_code.objects.get(pk=res).kcal
                        result3 += Bar_code.objects.get(pk=res).carbo
                        result4 += Bar_code.objects.get(pk=res).protein
                        result5 += Bar_code.objects.get(pk=res).fat
                        bar_list.append("총 제공량 : " + str(Bar_code.objects.get(pk=res).total)+"g" 
                        +" \t열량: "+ str(Bar_code.objects.get(pk=res).kcal)+"g" 
                        +" \t탄수화물: "+ str(Bar_code.objects.get(pk=res).carbo)+"g"
                        +" \t단백질: "+ str(Bar_code.objects.get(pk=res).protein)+"g"
                        +" \t지방: "+ str(Bar_code.objects.get(pk=res).fat)+"g")
            return render(request, 'cal_result.html', {'result1': result1, 'result2': result2, 'result3': result3, 'result4': result4, 'result5': result5, 'bar_list':bar_list})
    else:
        form = Multi_Upload()
    return render(request, 'upload_img_cal.html', {'form': form})

main/templates/cal_result.html
{% extends 'blog/base.html' %}
{% block content %}
<center>
    <br><br><br><br>
    <h1 style="font-weight:bold;color:rgb(137, 137, 240)">이 상품들의 영양성분은?</h1>
    {% for bar in bar_list %}
        <!-- {{ bar }}<br> -->
    {% endfor %}
    {% for bar in bar_list %}
        {{ bar }}<br>
    {% endfor %}


<br><br><br><br>
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>총 제공량</B></td>
            <td><B>총 열량</B></td>
            <td><B>총 탄수화물</B></td>
            <td><B>총 단백질</B></td>
            <td><B>총 지방</B></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><h1>{{ result1 }}g</h1></td>
            <td><h1>{{ result2 }}g</h1></td>
            <td><h1>{{ result3 }}g</h1></td>
            <td><h1>{{ result4 }}g</h1></td>
            <td><h1>{{ result5 }}g</h1></td>
        </tr>
        </tbody>
    </table>
    <br><br><br><br>
    <a href="{% url 'main:cal_result' %}" style="font-weight: bold;">다시하기</a>
    <br><br><br><br>
    <br><br><br><br>
</center>

{% endblock %}

main/templates/data_detail.html
{% block content %}
    {% if post.id %}

        <p>바코드 : {{ post.code }}</p>

    {% endif %}
    <br>
    <h1>상품명 : {{ post.name }}</h1>
    {% if post.image %}

        <img src="{{ post.image.url }}">

    {% endif %}
    <p>가격 : {{ post.charge }}</p>
    <a href="{% url 'main:data_update' post.code %}">상품수정</a>
    <div class="delete">
        <p><a href="{% url 'main:data_delete' post.code %}">삭제</a></p>  
    </div>
{% endblock %}

main/templates/data_list.html
<meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="shortcut icon" href="/static/icon/fav.ico">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        
    
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product_List</title>
    <style>
        .col-md-4 {
            float: left;
            max-width: 100%;
        }
        .card {
            height: 100%;
            margin: 5%;
            border: 2px solid #73AD21;
        }
    </style>
</head>
<body>
    <br><br><br><br><br><br>
    <center>

    <div class="row">
        {% if code_list %}
            {% for codes in code_list %}
            <div class="col-md-4">
                <div class="container">                
                    <div class="card">
                    <div class="card-body">
                    <h1 style="font-weight:bold; color:black"><a href="{% url 'main:data_detail' codes.code %}">{{ codes.name }}</a></h1>
                    <p style="font-weight:bold">바코드 [{{ codes.code }}]</p>
                    <p style="font-weight:bold; color:crimson">희망소비자가격 {{ codes.charge }}</p>
                    <p style="color:rgb(206, 199, 199)">등록일시 {{ codes.pub_date }}</p>
                </div>
            </div>
        </div>
    </div>
            {% endfor %}
        {% else %}
            <p>자료가 없습니다.</p>
        {% endif %}
    </div>   
    <br><br><br><br><br><br>
    <a href="{% url 'main:data_add' %}">상품추가</a><br>
    <br><br><br><br><br><br>
</center>
</body>
</html>
{% endblock content %}

main/templates/home.html
{% extends 'blog/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>제품목록</title>
    <style>
        .col-md-4 {
            float: left;
            max-width: 100%;
        }
        .card {
            height: 100%;
            margin: 5%;
            border: 2px solid #73AD21;
        }
    </style>
</head>


<body>
    <br><br>
        <center>
        <a href="{% url 'main:upload_image'%}"><img src= "/static/img/photosc.png"  alt="이미지 업로드" style="max-width: 20%; height:auto;" ></img></a>
        <a href="{% url 'main:upload_code' %}"><img src= "/static/img/codesc.png"   alt="이미지 업로드" style="max-width: 20%; height:auto;" ></img></a>
        <a href="{% url 'main:result' %}"><img src= "/static/img/sumsc.png"  alt="이미지 업로드" style="max-width: 20%; height:auto;" ></img></a>
        
    <br><br>
    <br><br>
    <br><br>
    <br><br>

    <img src= "/static/img/product.png" alt="제품"width="200"  ></center>

    <br><br>
    <div class="row">
    {% if code_list %}
        {% for codes in code_list %}
            <div class="col-md-4" >
                <div class="containers">                
                    <div class="card" >
                    <div class="card-body">
                    <h1 style="font-weight:bold; color:black"><a href="{% url 'main:product_detail' codes.code %}">{{ codes.name }}</a></h1>
                    <p style="font-weight:bold">바코드 [{{ codes.code }}]</p>
                    <p style="font-weight:bold; color:crimson">희망소비자가격 \{{ codes.charge }}</p>
                    <p style="color:rgb(206, 199, 199)">등록일시 {{ codes.pub_date }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% else %}
            <p>자료가 없습니다.</p>
        {% endif %}
    </div>
    <!-- <a href="{% url 'main:data_list' %}">데이터베이스</a><br> -->
    <!-- <a href="{% url 'main:upload_image' %}">이미지 제출</a><br> -->

    <br><br><br>
    <br><br><br><br> <br><br><br><br> <br><br><br><br>
    <footer class="text-muted">
        <div class="container">
          <p class="float-right">
            <a href="#" style="font-weight:bold ;color:red">맨 위로</a>
          </p>

    <center>
    <a href="{% url 'main:data_list' %}"><img src= "/static/img/data.png" alt="데이터베이스"width="40"  ></img></a>
    </center>

</body>
</html>

{% endblock content %}

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="shortcut icon" href="/static/icon/fav.ico">

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    
    <title>SMART CODE</title>
 
    </head>
<body>
    <center>
        <br><br><br><br>
    <img src= "/static/img/logo_big.png" alt="로고"width="500"  ></img>
    <br><br><br><br>
    
    <a href="{% url 'main:home' %}"><img src= "/static/img/start.png" alt="시작하기" width=300></img></a>
    
    </center>>

</body>
</html>

main/templates/introduce.html
{% extends 'blog/base.html' %}
{% block content %}

<!DOCTYPE html>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>스마트코드?</title>
    <style>
        .container {
            width:100vw;
            height:100vh;
        } 
        img {
          max-width: 100%;
          height: auto !important;
        }
    </style>
</head>

<body>
    <br><br>
    <div class="container">
   
       <img src= "/static/img/what.png" alt="스마트코드란"width="350"  ></img>
       <br><br><br><br>
        <img src= "/static/img/def.png" alt="정의"width="1200"  ></img>
        <br><br><br><br> <br><br><br><br> <br><br><br><br>
    
    
</body>
</html>

{% endblock content %}

main/templates/like.html
<h1>{{ post.name }}</h1>

<ul>
{% for choice in post.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'main:product_detail' post.code %}">Vote again?</a>

<!-- 사용안함 -->

main/templates/product_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    {% if post.id %}
    <br><br><br>
        <h2 style="color:skyblue;"> [{{ post.code }}]</h2>

    {% endif %}
    <br>
    <h1 style="font-weight:bold"> 상품명 [{{ post.manufacturer }}][{{ post.name }}]</h1>
    {% if post.image %}

        <img src="{{ post.image.url }}" width="400">

    {% endif %}
    <p style="font-weight:bold;color:crimson">희망소비자가격 \{{ post.charge }}</p>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <ul>
        {% for choice in post.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    
    <form action="{% url 'main:vote' post.code %}" method="POST"> <!--submit을 눌렀을 때 해당 url로 넘어감-->
        {% csrf_token %} <!--해킹 방지-->
        {% for choice in post.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"> <!--submit을 누르면 value값이 넘어감-->
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-dark">투표하기</button>
    </form>

        <form action="{% url 'main:comments_create' post.pk %}" method="post">
            {% csrf_token %}
            <br>
                  <input type="text" name="content"/>
                  <button type="submit" class="btn btn-dark">댓글달기</button>
        </form>
        <ul>
            {% for comment in post.review_set.all %}
                <span style="font-weight: bold;">└ {{ comment }}</span>    
                <span>{{ comment.pub_date }}</span>
                <a href="{% url 'main:comments_delete' post.pk comment.pk %}">Delete</a><br>
            {% endfor %}
        </ul>
        <a href="{% url 'main:home' %}">main으로 돌아가기</a>

        {% if post.total %}
            <p>총 제공량을 제외한 영양성분은 1회 제공량이 기준입니다</p>
            <p>1회 제공량 : {{ post.once }}g</p>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td><B>총 제공량</B></td>
                    <td><B>열량</B></td>
                    <td><B>탄수화물</B></td>
                    <td><B>당류</B></td>
                    <td><B>단백질</B></td>
                    <td><B>지방</B></td>
                    <td><B>포화지방</B></td>
                    <td><B>트렌스지방</B></td>
                    <td><B>콜레스트롤</B></td>
                    <td><B>나트륨</B></td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ post.total }}g</td>
                    <td>{{ post.kcal }}g</td>
                    <td>{{ post.carbo }}g</td>
                    <td>{{ post.sugar }}g</td>
                    <td>{{ post.protein }}g</td>
                    <td>{{ post.fat }}g</td>
                    <td>{{ post.sat_fat }}g</td>
                    <td>{{ post.tra_fat }}g</td>
                    <td>{{ post.colestrol }}g</td>
                    <td>{{ post.natrium }}g</td>
                </tr>
                </tbody>
            </table>
        {% endif %}   
</div>
<br><br><br><br><br> <br><br><br><br> <br><br><br><br> <br><br><br><br>
{% endblock %}

main/templates/result.html
{% extends 'blog/base.html' %}
{% block content %}
<br><br><br>
<center>
    <img src= "/static/img/list.png" alt="제품"width="150"  >

    <h5 style="color:crimson;font-weight:bold;">--------------------------------------------</h5>
        <h5 style="color:rgb(92, 63, 63);font-weight:bold">{% for bar in bar_list %}
        +{{ bar }}<br>
    {% endfor %}</h5>

<br><br><br><br><br><br><br>
<h5 style="color:crimson;font-weight:bold;">--------------------------------------------</h5>
<h3 style="font-weight:bold;color:crimson">=총 희망소비자가격 \{{ result }}원</h3>
<br><br><br><br>
    <a style="font-weight:bold;color:crimson" href="{% url 'main:home' %}">다시하기</a>
        </center>
{% endblock %}

main/templates/review.html
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">댓글 등록</button>
    </form>
    <br><br>

    
{% endblock %}

main/templates/upload_img.html
{% extends 'blog/base.html' %}
{% block content %}
&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp 
<br><br>
<center>
    <img src= "/static/img/sch.png" alt="사진검색"width="180"></img>
    <br><br><br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        
     <button type="submit" class="btn btn-danger">비교하기</button>

    </form>
    {% if message %}
        {{ message }}
    {% endif %}
    <br><br><br><br> <br><br><br><br> <br><br><br><br>
</center>

    
{% endblock content %}

main/templates/upload_img_cal.html
{% extends 'blog/base.html' %}
{% block content %}
&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp 
<br><br>
<center>
    <img src= "/static/img/total.png" alt="사진검색"width="220"></img>
    <br><br><br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        
     <button type="submit" class="btn btn-danger">계산하기</button>

    </form>
    {% if message %}
        {{ message }}
    {% endif %}
    <br><br><br><br> <br><br><br><br> <br><br><br><br>
</center>

    
{% endblock content %}

main/templates/upload_img_total.html
{% extends 'blog/base.html' %}
{% block content %}
&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp &nbsp 
<br><br>
<center>
    <img src= "/static/img/circ.png" alt="사진검색"width="180"></img>

    <br><br><br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        
     <button type="submit" class="btn btn-danger">계산하기</button>
     <br><br>
    {% if message %}
        {{ message }}
    {% endif %}
    <br>
    <img src= "/static/img/notice.png" alt="사진검색"width="300"></img>
    </form>
    <br><br><br><br> <br><br><br><br> <br><br><br><br>

</center>

    
{% endblock content %}

main/templates/user_create.html
<title>회원 가입</title>


<h1>가입하기</h1>
    <form class="post-form" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.errors }} 
    <div class="form-group">
        <label for="id_{{ field.html_name}}">{{ field.label }}</label>
        {{ field }}
    </div>
        {% endfor %}
        <div>
            <button type="submit">가입하기</button>
        </div>
    </form>